project:
  type: website
  output-dir: _site
  resources:
    - Logos/
    - styles.css

website:
  title: "South Okanagan Bat Hibernacula Project"
  site-url: https://bp-sensr.github.io/Okanagan-WinterMonitoring/